name: Slow Tests

on: push

jobs:
  android:
    name: Build for Android
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@v3
    - run: rustup toolchain install $(cat rust-toolchain) --profile minimal --target aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
    - run: bin/fetch-artifact -p android
    - run: bin/build-aar --release --ringrtc-only
    - name: Upload libraries
      uses: actions/upload-artifact@v3
      with:
        name: libs
        path: out/release/libs/*
        retention-days: 2

  android-emulator-tests:
    name: Android Emulator Tests
    # For hardware acceleration; see https://github.com/ReactiveCircus/android-emulator-runner/issues/46
    runs-on: buildjet-4vcpu-ubuntu-2204	
    needs: [android]
    if: ${{ always() && needs.android.result == 'success' }}

    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x86_64]

    steps:
      - run: 'echo "JAVA_HOME=$JAVA_HOME_11_X64" >> "$GITHUB_ENV"'

      - uses: actions/checkout@v3

      - name: Download JNI libraries
        id: download
        uses: actions/download-artifact@v3
        with:
          name: libs
          path: out/release/libs

      # From reactivecircus/android-emulator-runner
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.arch }}-21

      - name: Create AVD and generate snapshot for caching
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: ${{ matrix.arch }}
          api-level: 21
          force-avd-creation: false
          emulator-options: -no-window -noaudio -no-boot-anim
          script: echo "Generated AVD snapshot for caching."

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: ${{ matrix.arch }}
          api-level: 21
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim
          # It is correct that we use *debug*RingrtcLibDir below (specified by connectedCheck),
          # even though we are using *release* artifacts.
          script: ./gradlew ringrtc:android:connectedCheck -PdebugRingrtcLibDir=${{ github.workspace }}/out/release/libs -PwebrtcJar=${{ github.workspace }}/out/release/libs/libwebrtc.jar

